### ISSUE TITLE
Create mock-ups

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/3DBIONOTES#10]
- [x] Home page with header from https://3dbionotes.cnb.csic.es/ws/home
- [x] COVID-19 with local header
* We need a footer

- Discussed layout for COVID-19
-> Search by entry ID
-> Selected Entries: EMD-7573 | EMD-8069 | 6ACG. Carousel?
-> SARS-CoV-2 virus proteome. Redesign?
-> Text below the proteome
-> Live search
-> A table per protein
-> External data sources and collaborations

Useful links:
- http://haml.info/tutorial.html
- https://github.com/twbs/bootstrap-rubygem => version 4.4.1
https://htmltohaml.com/

- [x] Tooltip
Name
Title
Related PDB
EMDB External Example Link (take Title from there): https://www.emdataresource.org/EMD-21457
- [x] Proteoma Legend
Proteome Table Legend below:
Non-structural protein (NSXx): Oranges
Spike (S):
Membrane protein (M):
Nucleo Protein (N)
Envelope Protein (E)
Hypothetical Protein - Open Reading Frame (NS10): It is not clear yet if it is a protein
- [x] Collapsable boxes
- [x] External link to footer

Uploaded to Google Drive since PDF file is too big (20,2 MB): https://drive.google.com/open?id=1h_ynjFHxdR8lgHqFtGk3YwHfM8MM9TF3

('git pull' <- To fetch latest changes)
LOCAL SERVER START COMMANDS:
rvm use ruby-2.4.1
bundle exec rails server

**Comment by raydario** [comment]
Uploaded to Google Drive since PDF file is too big (20,2 MB): https://drive.google.com/file/d/1So2OB9dqjwV5Qle4vcRbW4IfYwxgNISh/view?usp=sharing

**Comment by adrianq** [comment]
Thanks @raydario Looks awesome! I have sent them to the client. Waiting for feedback.

**Comment by adrianq** [comment]
Comments from the client:
- Remove Protein image from table
- Add subcontainers in computational model (nested)
- Labels (as PDB-redo and Isolde) needs to be a bit bigger
- Limited items to XX for container. Add pager in header (XX out of 500). On click, open a modal
