### ISSUE TITLE
Implement COVID-19 webpage

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/3DBIONOTES#12]
Comments from the client to the mock-up:
- [x] Add subcontainers in computational model (nested)
- [x] Add anchor to proteoma (NSP1 and PL-Pro)
- [x] Modal/Dialog on-click
- [x] External data sources text at the bottom
- [x] Make panel collapsable
- [x] Design hover panel

URL: http://campins.cnb.csic.es:8080/ws/database

![image](https://app.gitkraken.com/api/glo/boards/5e9dbc20e93c0a001191213d/attachments/5e9dc15ef95f6f0011e873f9)

[3DBionotes Web Covid19.zip](https://app.gitkraken.com/api/glo/boards/5e9dbc20e93c0a001191213d/attachments/5eaa58d6bda0ec001339a944)

**Comment by raydario** [comment]
Uploaded zip file with the recent changes. 

Please note that popover.js and carousel.js files were added, they are required for those functionalities.

For the Collapse Toggle Icon to switch appearance it should change its tag <i> to the class="fa fa-chevron-down" when closed (collapsed) 
See reference:
https://stackoverflow.com/questions/14882404/twitter-bootstrap-accordion-icon-doesnt-change
