### ISSUE TITLE
Make COVID-19 dynamic

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/3DBIONOTES#14]
JSON FORMAT
```
“EntryName": {
        "names": [],
        "PDB": [],
        "EMDB": [],
        "CompModels": [],
        "Interactions": {
            "PPComplex": [],
            "Ligands": []
        },
        "Related": {}
    },
```
Latest JSON file can be found at: https://drive.google.com/file/d/1d7e2FI8cX7B9nw_Q20q_dKNIK1roNic5/view?usp=sharing

We will have to create a new controller but an example of the one they are using can be found at: https://github.com/3dbionotes-community/3DBIONOTES/blob/feature/CoVid19-outbreak/app/controllers/cv19_controller.rb

Btw, if you can give it a try to a merge with the feature/CoVid19-outbreak branch it would be great so we avoid major conflicts in the future

---

 - Object key is the protein name.
 - names: list of tags.
- PDB Thumbnail url: `https://www.ebi.ac.uk/pdbe/static/entry/ + ID + _deposited_chain_front_image-200x200.png` + resize (100x100?)
- link/query/img look fixed. Remove them.
```
         "ext_link": "https://www.ebi.ac.uk/pdbe/entry/pdb/6w9c",
         "query": "/?queryId=6w9c&viewer_type=ngl&button=#query",
         "img": "https://www.ebi.ac.uk/pdbe/static/entry/6w9c_deposited_chain_front_image-00x200.png"
```
- Links:
pdb ->https://www.rcsb.org/structure/6y2e
emdb -> https://www.ebi.ac.uk/pdbe/entry/emdb/EMD-21457
- Images: 6m17 -> 6[m1]7 -> m1 -> https://cdn.rcsb.org/images/rutgers/m1/6m17/6m17.pdb1-500.jpg

**Comment by tokland** [comment]
- [ ] From mock-up: collapsable
- [ ] From mock-up: tooltip shows on click, shoud show on hover. a -> img + h6.
