### ISSUE TITLE
Review metadata for pages

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/3DBIONOTES#20]
Check if they want to add more metadata:
Added description, author & copyright (contents to be confirmed) but there are more metadata available to add, check this resource:
https://gist.github.com/MicBrain/46a9723158307fd30db66a4b2af85411

@raydario let me know if there is anything you don't know how to fill...

**Comment by raydario** [comment]
Added recommended metadata, maybe add a keyword list also? @adrianq
