### ISSUE TITLE
Mock-ups for Drug Repurposing

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/3DBIONOTES#50]
Mock-up https://docs.google.com/drawings/d/1h47s3fz3PSAnyXcFJc-1cIheExkbCEm41b5_doDKHzI/edit

- One single page
- Header: Logo | Title (COVID-19 Drug Repurposing) | Logo funders
- Body Sections
   - Description of the page: Lorem ipsum 
   - Filter boxes: Protein | PDB | Pocket. Each one depends on the previous one
   - Table with search box, action to download table content and pager. Potentially collapsable
   - Table Header with sorting by column and (i) icon in n columns
  - Table with content in the mock-up document. Note we will have four actions per row. Note we need lightboxes for the images in the table.
  - Top-right side panel:  title - Pocket Info and bindings and description- lorem ipsum. Potentially collapsable
  - Bottom -right side panel with 3DViewer
- Footer: Same layout as in 3DBionotes changing name with "COVID-19 Drug Repurposing"
- Logo needs to be created
[COVID-19 Drug Repurposing.pdf](https://app.gitkraken.com/api/glo/boards/5e9dbc20e93c0a001191213d/attachments/5ec66c243c5016001672e19f)

[COVID-19 Drug Repurposing.zip](https://app.gitkraken.com/api/glo/boards/5e9dbc20e93c0a001191213d/attachments/5eccdc273c5016001673d9bd)

**Comment by raydario** [comment]
Attached two mockup versions with different color schemes

**Comment by raydario** [comment]
Another version (V3), i think that is the best one

**Comment by adrianq** [comment]
They look great @raydario !  Just a few comments:
- 'Pocket info and binding' needs to be a panel. It is not the title of the viewer See -> Top-right side panel: title - Pocket Info and bindings and description- lorem ipsum. Potentially collapsable. So that we have on the left side the table and on the right side two panels: (1) Title: 'Pocket info and bindings' Body: Lorem ipsum (2) the viewer
- In the footer, can you please remove the mention to 3DBionotes?
- Any chance, we could see the table title 'Drug Interaction'? I know this is a bit picky but it is the first thing the client is gonna say about the mock-up. 
- Can you illustrate how the three drop-downs are gonna look? For instance, show the 'Protein' with something select, show the 'PDB target' open showing the option and show the 'Pocket' disabled as the 'PDB target' has not been selected yet.

**Comment by raydario** [comment]
Please check the changes

**Comment by raydario** [comment]
About Styling and disabling Select Inputs: https://stackoverflow.com/questions/59716685/bootstrap-select-dropdown-on-change-open-another-bootstrap-select-dropdown
