### ISSUE TITLE
Review styles in http://3dbionotes.cnb.csic.es/ws/database

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/3DBIONOTES#54]

**Comment by raydario** [comment]
Not sure what I have to review here... @adrianq

**Comment by raydario** [comment]
BTW I am out of EyeSeeTea-Web workspace (we have to set unassigned time entries)

**Comment by adrianq** [comment]
Just the text, below the submit button. It looks to me we messed up the styles...

We can have a look at the entries in toggl together in our meeting
