### ISSUE TITLE
Inject Drug Repurposing web html and make it dynamic

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/3DBIONOTES#63]
Static HTML can be found here -> https://drive.google.com/file/d/1WnOe-E4O6MAeCQtM-5dwnIpex6xmvAUO/view?usp=sharing
We will go for the implementation without viewer

See Ray comment about disabling dropdowns:
About Styling and disabling Select Inputs: https://stackoverflow.com/questions/59716685/bootstrap-select-dropdown-on-change-open-another-bootstrap-select-dropdown

See Notes: https://docs.google.com/document/d/13IHOsRH0JJQwKLiMPuWiCWCHcFg0YWMLs5G0894WyQo/edit

JSON for the DB: https://drive.google.com/drive/u/0/folders/1oUGc6WyBQ2t3KRjxCMJSBWg8UdjbUBhw

**Comment by tokland** [comment]
- [ ] move API / -> /api
- [ ]  add page to Django
- [ ]  build react page
- [ ]  add component to page /
- [ ]  analytics (comentado!)
- [ ]  pagination
- [ ]  interaction: image URL
- [ ]  image -> lightbox
- [ ]  download pocket (filename: protein-pdb-pocket.zip)
- [ ]  download interaction
- [ ]  Update README
- [ ]  docker tasks (misc to fix)
