### ISSUE TITLE
Integrate google docs as an iframe in the help section

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/3DBIONOTES#76]
This is the doc https://docs.google.com/document/d/1ts3452QJhCriFkOyMfPdPnPGtz_6QNTVrq1FDeH4V5E/edit#heading=h.e2cxjrbemxvp

The doc to be integrated https://docs.google.com/document/d/e/2PACX-1vS11ylBB0USslByZQZUi0-0eB3BUlHuKulxFki_KUzsVPVRnyn7wVIKwIxu53XyCZvxsg-cTkLtMT2d/pub?embedded=true

and the html code: 
<iframe src="https://docs.google.com/document/d/e/2PACX-1vS11ylBB0USslByZQZUi0-0eB3BUlHuKulxFki_KUzsVPVRnyn7wVIKwIxu53XyCZvxsg-cTkLtMT2d/pub?embedded=true"></iframe>

See https://codepen.io/pconesa/pen/NWxbbdV for a code example

**Comment by raydario** [comment]
Should this replace the HTML content from the Help section? This would make the relative links at the Help introduction unusable... (just to confirm)

**Comment by adrianq** [comment]
Yep, exactly that

**Comment by raydario** [comment]
To make the iframe adjust height based on inside content: https://stackoverflow.com/questions/819416/adjust-width-and-height-of-iframe-to-fit-with-content-in-it

**Comment by raydario** [comment]
Ready to push (without height adjust)
