### ISSUE TITLE
Add image of the virus with the proteime

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/3DBIONOTES#77]
https://www.nejm.org/doi/full/10.1056/NEJMcibr2007042 (figure 1)

Can we maybe the image so that depending on where you click you go to a different section?

**Comment by raydario** [comment]
Yes this can be done, do we have permission to use that image?

**Comment by adrianq** [comment]
I am trying to figure it out. I guess to cite the paper should be enough but I will double check and come back to you

**Comment by raydario** [comment]
To be able to resize the imagemap: https://github.com/davidjbradshaw/image-map-resizer

**Comment by raydario** [comment]
Ready to push
